;; title: froggy-batch-premint
;; version: 1.0.0
;; summary: Batch premint wrapper for Froggy NFTs
;; description: Allows users to premint multiple Froggy NFTs in a single transaction

(use-trait nft-trait 'SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.nft-trait.nft-trait)
(use-trait ft-trait 'SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard.sip-010-trait)

;; Constants
(define-constant CONTRACT-OWNER tx-sender)
(define-constant ERR-NOT-AUTHORIZED (err u400))
(define-constant ERR-PREMINT-FAILED (err u402))
(define-constant ERR-PAUSED (err u403))

;; Contract references
(define-constant MARKETPLACE 'SPV9K21TBFAK4KNRJXF5DFP8N7W46G4V9RCJDC22.froggy-nft-marketplace)
(define-constant NFT-CONTRACT 'SPV9K21TBFAK4KNRJXF5DFP8N7W46G4V9RCJDC22.froggy-gamma-nft)
(define-constant FT-CONTRACT 'SP3E8B51MF5E28BD82FM95VDSQ71VK4KFNZX7ZK2R.frog-faktory)

;; Data vars
(define-data-var contract-paused bool false)

;; Admin functions
(define-public (set-paused (paused bool))
  (begin
    (asserts! (is-eq tx-sender CONTRACT-OWNER) ERR-NOT-AUTHORIZED)
    (var-set contract-paused paused)
    (ok true)))

;; Batch premint functions - explicit calls since fold can't carry traits
;; Available sizes: 5, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 150, 200

(define-public (premint-5
  (t1 uint) (t2 uint) (t3 uint) (t4 uint) (t5 uint)
  (nft-contract <nft-trait>) (ft-contract <ft-trait>))
  (begin
    (asserts! (not (var-get contract-paused)) ERR-PAUSED)
    (try! (contract-call? MARKETPLACE premint t1 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t2 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t3 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t4 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t5 nft-contract ft-contract))
    (print { event: "batch-premint", buyer: tx-sender, count: u5 })
    (ok u5)))

(define-public (premint-10
  (t1 uint) (t2 uint) (t3 uint) (t4 uint) (t5 uint)
  (t6 uint) (t7 uint) (t8 uint) (t9 uint) (t10 uint)
  (nft-contract <nft-trait>) (ft-contract <ft-trait>))
  (begin
    (asserts! (not (var-get contract-paused)) ERR-PAUSED)
    (try! (contract-call? MARKETPLACE premint t1 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t2 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t3 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t4 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t5 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t6 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t7 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t8 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t9 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t10 nft-contract ft-contract))
    (print { event: "batch-premint", buyer: tx-sender, count: u10 })
    (ok u10)))

(define-public (premint-20
  (t1 uint) (t2 uint) (t3 uint) (t4 uint) (t5 uint)
  (t6 uint) (t7 uint) (t8 uint) (t9 uint) (t10 uint)
  (t11 uint) (t12 uint) (t13 uint) (t14 uint) (t15 uint)
  (t16 uint) (t17 uint) (t18 uint) (t19 uint) (t20 uint)
  (nft-contract <nft-trait>) (ft-contract <ft-trait>))
  (begin
    (asserts! (not (var-get contract-paused)) ERR-PAUSED)
    (try! (contract-call? MARKETPLACE premint t1 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t2 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t3 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t4 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t5 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t6 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t7 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t8 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t9 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t10 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t11 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t12 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t13 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t14 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t15 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t16 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t17 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t18 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t19 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t20 nft-contract ft-contract))
    (print { event: "batch-premint", buyer: tx-sender, count: u20 })
    (ok u20)))

(define-public (premint-30
  (t1 uint) (t2 uint) (t3 uint) (t4 uint) (t5 uint)
  (t6 uint) (t7 uint) (t8 uint) (t9 uint) (t10 uint)
  (t11 uint) (t12 uint) (t13 uint) (t14 uint) (t15 uint)
  (t16 uint) (t17 uint) (t18 uint) (t19 uint) (t20 uint)
  (t21 uint) (t22 uint) (t23 uint) (t24 uint) (t25 uint)
  (t26 uint) (t27 uint) (t28 uint) (t29 uint) (t30 uint)
  (nft-contract <nft-trait>) (ft-contract <ft-trait>))
  (begin
    (asserts! (not (var-get contract-paused)) ERR-PAUSED)
    (try! (contract-call? MARKETPLACE premint t1 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t2 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t3 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t4 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t5 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t6 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t7 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t8 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t9 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t10 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t11 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t12 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t13 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t14 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t15 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t16 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t17 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t18 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t19 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t20 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t21 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t22 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t23 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t24 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t25 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t26 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t27 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t28 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t29 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t30 nft-contract ft-contract))
    (print { event: "batch-premint", buyer: tx-sender, count: u30 })
    (ok u30)))

(define-public (premint-40
  (t1 uint) (t2 uint) (t3 uint) (t4 uint) (t5 uint)
  (t6 uint) (t7 uint) (t8 uint) (t9 uint) (t10 uint)
  (t11 uint) (t12 uint) (t13 uint) (t14 uint) (t15 uint)
  (t16 uint) (t17 uint) (t18 uint) (t19 uint) (t20 uint)
  (t21 uint) (t22 uint) (t23 uint) (t24 uint) (t25 uint)
  (t26 uint) (t27 uint) (t28 uint) (t29 uint) (t30 uint)
  (t31 uint) (t32 uint) (t33 uint) (t34 uint) (t35 uint)
  (t36 uint) (t37 uint) (t38 uint) (t39 uint) (t40 uint)
  (nft-contract <nft-trait>) (ft-contract <ft-trait>))
  (begin
    (asserts! (not (var-get contract-paused)) ERR-PAUSED)
    (try! (contract-call? MARKETPLACE premint t1 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t2 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t3 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t4 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t5 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t6 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t7 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t8 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t9 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t10 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t11 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t12 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t13 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t14 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t15 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t16 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t17 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t18 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t19 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t20 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t21 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t22 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t23 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t24 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t25 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t26 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t27 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t28 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t29 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t30 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t31 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t32 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t33 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t34 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t35 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t36 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t37 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t38 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t39 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t40 nft-contract ft-contract))
    (print { event: "batch-premint", buyer: tx-sender, count: u40 })
    (ok u40)))

(define-public (premint-50
  (t1 uint) (t2 uint) (t3 uint) (t4 uint) (t5 uint)
  (t6 uint) (t7 uint) (t8 uint) (t9 uint) (t10 uint)
  (t11 uint) (t12 uint) (t13 uint) (t14 uint) (t15 uint)
  (t16 uint) (t17 uint) (t18 uint) (t19 uint) (t20 uint)
  (t21 uint) (t22 uint) (t23 uint) (t24 uint) (t25 uint)
  (t26 uint) (t27 uint) (t28 uint) (t29 uint) (t30 uint)
  (t31 uint) (t32 uint) (t33 uint) (t34 uint) (t35 uint)
  (t36 uint) (t37 uint) (t38 uint) (t39 uint) (t40 uint)
  (t41 uint) (t42 uint) (t43 uint) (t44 uint) (t45 uint)
  (t46 uint) (t47 uint) (t48 uint) (t49 uint) (t50 uint)
  (nft-contract <nft-trait>) (ft-contract <ft-trait>))
  (begin
    (asserts! (not (var-get contract-paused)) ERR-PAUSED)
    (try! (contract-call? MARKETPLACE premint t1 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t2 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t3 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t4 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t5 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t6 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t7 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t8 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t9 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t10 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t11 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t12 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t13 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t14 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t15 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t16 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t17 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t18 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t19 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t20 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t21 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t22 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t23 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t24 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t25 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t26 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t27 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t28 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t29 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t30 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t31 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t32 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t33 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t34 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t35 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t36 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t37 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t38 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t39 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t40 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t41 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t42 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t43 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t44 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t45 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t46 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t47 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t48 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t49 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t50 nft-contract ft-contract))
    (print { event: "batch-premint", buyer: tx-sender, count: u50 })
    (ok u50)))

(define-public (premint-60
  (t1 uint) (t2 uint) (t3 uint) (t4 uint) (t5 uint)
  (t6 uint) (t7 uint) (t8 uint) (t9 uint) (t10 uint)
  (t11 uint) (t12 uint) (t13 uint) (t14 uint) (t15 uint)
  (t16 uint) (t17 uint) (t18 uint) (t19 uint) (t20 uint)
  (t21 uint) (t22 uint) (t23 uint) (t24 uint) (t25 uint)
  (t26 uint) (t27 uint) (t28 uint) (t29 uint) (t30 uint)
  (t31 uint) (t32 uint) (t33 uint) (t34 uint) (t35 uint)
  (t36 uint) (t37 uint) (t38 uint) (t39 uint) (t40 uint)
  (t41 uint) (t42 uint) (t43 uint) (t44 uint) (t45 uint)
  (t46 uint) (t47 uint) (t48 uint) (t49 uint) (t50 uint)
  (t51 uint) (t52 uint) (t53 uint) (t54 uint) (t55 uint)
  (t56 uint) (t57 uint) (t58 uint) (t59 uint) (t60 uint)
  (nft-contract <nft-trait>) (ft-contract <ft-trait>))
  (begin
    (asserts! (not (var-get contract-paused)) ERR-PAUSED)
    (try! (contract-call? MARKETPLACE premint t1 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t2 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t3 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t4 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t5 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t6 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t7 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t8 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t9 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t10 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t11 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t12 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t13 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t14 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t15 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t16 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t17 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t18 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t19 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t20 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t21 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t22 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t23 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t24 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t25 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t26 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t27 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t28 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t29 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t30 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t31 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t32 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t33 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t34 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t35 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t36 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t37 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t38 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t39 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t40 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t41 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t42 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t43 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t44 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t45 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t46 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t47 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t48 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t49 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t50 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t51 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t52 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t53 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t54 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t55 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t56 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t57 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t58 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t59 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t60 nft-contract ft-contract))
    (print { event: "batch-premint", buyer: tx-sender, count: u60 })
    (ok u60)))

(define-public (premint-70
  (t1 uint) (t2 uint) (t3 uint) (t4 uint) (t5 uint)
  (t6 uint) (t7 uint) (t8 uint) (t9 uint) (t10 uint)
  (t11 uint) (t12 uint) (t13 uint) (t14 uint) (t15 uint)
  (t16 uint) (t17 uint) (t18 uint) (t19 uint) (t20 uint)
  (t21 uint) (t22 uint) (t23 uint) (t24 uint) (t25 uint)
  (t26 uint) (t27 uint) (t28 uint) (t29 uint) (t30 uint)
  (t31 uint) (t32 uint) (t33 uint) (t34 uint) (t35 uint)
  (t36 uint) (t37 uint) (t38 uint) (t39 uint) (t40 uint)
  (t41 uint) (t42 uint) (t43 uint) (t44 uint) (t45 uint)
  (t46 uint) (t47 uint) (t48 uint) (t49 uint) (t50 uint)
  (t51 uint) (t52 uint) (t53 uint) (t54 uint) (t55 uint)
  (t56 uint) (t57 uint) (t58 uint) (t59 uint) (t60 uint)
  (t61 uint) (t62 uint) (t63 uint) (t64 uint) (t65 uint)
  (t66 uint) (t67 uint) (t68 uint) (t69 uint) (t70 uint)
  (nft-contract <nft-trait>) (ft-contract <ft-trait>))
  (begin
    (asserts! (not (var-get contract-paused)) ERR-PAUSED)
    (try! (contract-call? MARKETPLACE premint t1 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t2 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t3 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t4 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t5 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t6 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t7 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t8 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t9 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t10 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t11 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t12 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t13 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t14 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t15 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t16 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t17 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t18 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t19 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t20 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t21 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t22 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t23 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t24 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t25 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t26 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t27 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t28 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t29 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t30 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t31 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t32 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t33 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t34 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t35 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t36 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t37 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t38 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t39 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t40 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t41 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t42 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t43 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t44 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t45 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t46 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t47 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t48 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t49 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t50 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t51 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t52 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t53 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t54 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t55 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t56 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t57 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t58 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t59 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t60 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t61 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t62 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t63 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t64 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t65 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t66 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t67 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t68 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t69 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t70 nft-contract ft-contract))
    (print { event: "batch-premint", buyer: tx-sender, count: u70 })
    (ok u70)))

(define-public (premint-80
  (t1 uint) (t2 uint) (t3 uint) (t4 uint) (t5 uint)
  (t6 uint) (t7 uint) (t8 uint) (t9 uint) (t10 uint)
  (t11 uint) (t12 uint) (t13 uint) (t14 uint) (t15 uint)
  (t16 uint) (t17 uint) (t18 uint) (t19 uint) (t20 uint)
  (t21 uint) (t22 uint) (t23 uint) (t24 uint) (t25 uint)
  (t26 uint) (t27 uint) (t28 uint) (t29 uint) (t30 uint)
  (t31 uint) (t32 uint) (t33 uint) (t34 uint) (t35 uint)
  (t36 uint) (t37 uint) (t38 uint) (t39 uint) (t40 uint)
  (t41 uint) (t42 uint) (t43 uint) (t44 uint) (t45 uint)
  (t46 uint) (t47 uint) (t48 uint) (t49 uint) (t50 uint)
  (t51 uint) (t52 uint) (t53 uint) (t54 uint) (t55 uint)
  (t56 uint) (t57 uint) (t58 uint) (t59 uint) (t60 uint)
  (t61 uint) (t62 uint) (t63 uint) (t64 uint) (t65 uint)
  (t66 uint) (t67 uint) (t68 uint) (t69 uint) (t70 uint)
  (t71 uint) (t72 uint) (t73 uint) (t74 uint) (t75 uint)
  (t76 uint) (t77 uint) (t78 uint) (t79 uint) (t80 uint)
  (nft-contract <nft-trait>) (ft-contract <ft-trait>))
  (begin
    (asserts! (not (var-get contract-paused)) ERR-PAUSED)
    (try! (contract-call? MARKETPLACE premint t1 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t2 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t3 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t4 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t5 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t6 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t7 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t8 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t9 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t10 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t11 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t12 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t13 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t14 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t15 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t16 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t17 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t18 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t19 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t20 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t21 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t22 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t23 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t24 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t25 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t26 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t27 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t28 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t29 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t30 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t31 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t32 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t33 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t34 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t35 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t36 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t37 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t38 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t39 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t40 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t41 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t42 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t43 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t44 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t45 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t46 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t47 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t48 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t49 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t50 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t51 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t52 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t53 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t54 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t55 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t56 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t57 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t58 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t59 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t60 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t61 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t62 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t63 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t64 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t65 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t66 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t67 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t68 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t69 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t70 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t71 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t72 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t73 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t74 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t75 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t76 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t77 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t78 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t79 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t80 nft-contract ft-contract))
    (print { event: "batch-premint", buyer: tx-sender, count: u80 })
    (ok u80)))

(define-public (premint-90
  (t1 uint) (t2 uint) (t3 uint) (t4 uint) (t5 uint)
  (t6 uint) (t7 uint) (t8 uint) (t9 uint) (t10 uint)
  (t11 uint) (t12 uint) (t13 uint) (t14 uint) (t15 uint)
  (t16 uint) (t17 uint) (t18 uint) (t19 uint) (t20 uint)
  (t21 uint) (t22 uint) (t23 uint) (t24 uint) (t25 uint)
  (t26 uint) (t27 uint) (t28 uint) (t29 uint) (t30 uint)
  (t31 uint) (t32 uint) (t33 uint) (t34 uint) (t35 uint)
  (t36 uint) (t37 uint) (t38 uint) (t39 uint) (t40 uint)
  (t41 uint) (t42 uint) (t43 uint) (t44 uint) (t45 uint)
  (t46 uint) (t47 uint) (t48 uint) (t49 uint) (t50 uint)
  (t51 uint) (t52 uint) (t53 uint) (t54 uint) (t55 uint)
  (t56 uint) (t57 uint) (t58 uint) (t59 uint) (t60 uint)
  (t61 uint) (t62 uint) (t63 uint) (t64 uint) (t65 uint)
  (t66 uint) (t67 uint) (t68 uint) (t69 uint) (t70 uint)
  (t71 uint) (t72 uint) (t73 uint) (t74 uint) (t75 uint)
  (t76 uint) (t77 uint) (t78 uint) (t79 uint) (t80 uint)
  (t81 uint) (t82 uint) (t83 uint) (t84 uint) (t85 uint)
  (t86 uint) (t87 uint) (t88 uint) (t89 uint) (t90 uint)
  (nft-contract <nft-trait>) (ft-contract <ft-trait>))
  (begin
    (asserts! (not (var-get contract-paused)) ERR-PAUSED)
    (try! (contract-call? MARKETPLACE premint t1 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t2 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t3 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t4 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t5 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t6 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t7 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t8 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t9 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t10 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t11 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t12 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t13 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t14 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t15 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t16 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t17 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t18 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t19 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t20 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t21 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t22 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t23 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t24 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t25 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t26 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t27 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t28 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t29 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t30 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t31 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t32 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t33 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t34 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t35 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t36 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t37 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t38 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t39 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t40 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t41 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t42 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t43 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t44 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t45 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t46 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t47 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t48 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t49 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t50 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t51 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t52 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t53 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t54 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t55 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t56 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t57 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t58 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t59 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t60 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t61 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t62 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t63 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t64 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t65 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t66 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t67 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t68 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t69 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t70 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t71 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t72 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t73 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t74 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t75 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t76 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t77 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t78 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t79 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t80 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t81 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t82 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t83 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t84 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t85 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t86 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t87 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t88 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t89 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t90 nft-contract ft-contract))
    (print { event: "batch-premint", buyer: tx-sender, count: u90 })
    (ok u90)))

(define-public (premint-100
  (t1 uint) (t2 uint) (t3 uint) (t4 uint) (t5 uint)
  (t6 uint) (t7 uint) (t8 uint) (t9 uint) (t10 uint)
  (t11 uint) (t12 uint) (t13 uint) (t14 uint) (t15 uint)
  (t16 uint) (t17 uint) (t18 uint) (t19 uint) (t20 uint)
  (t21 uint) (t22 uint) (t23 uint) (t24 uint) (t25 uint)
  (t26 uint) (t27 uint) (t28 uint) (t29 uint) (t30 uint)
  (t31 uint) (t32 uint) (t33 uint) (t34 uint) (t35 uint)
  (t36 uint) (t37 uint) (t38 uint) (t39 uint) (t40 uint)
  (t41 uint) (t42 uint) (t43 uint) (t44 uint) (t45 uint)
  (t46 uint) (t47 uint) (t48 uint) (t49 uint) (t50 uint)
  (t51 uint) (t52 uint) (t53 uint) (t54 uint) (t55 uint)
  (t56 uint) (t57 uint) (t58 uint) (t59 uint) (t60 uint)
  (t61 uint) (t62 uint) (t63 uint) (t64 uint) (t65 uint)
  (t66 uint) (t67 uint) (t68 uint) (t69 uint) (t70 uint)
  (t71 uint) (t72 uint) (t73 uint) (t74 uint) (t75 uint)
  (t76 uint) (t77 uint) (t78 uint) (t79 uint) (t80 uint)
  (t81 uint) (t82 uint) (t83 uint) (t84 uint) (t85 uint)
  (t86 uint) (t87 uint) (t88 uint) (t89 uint) (t90 uint)
  (t91 uint) (t92 uint) (t93 uint) (t94 uint) (t95 uint)
  (t96 uint) (t97 uint) (t98 uint) (t99 uint) (t100 uint)
  (nft-contract <nft-trait>) (ft-contract <ft-trait>))
  (begin
    (asserts! (not (var-get contract-paused)) ERR-PAUSED)
    (try! (contract-call? MARKETPLACE premint t1 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t2 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t3 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t4 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t5 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t6 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t7 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t8 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t9 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t10 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t11 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t12 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t13 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t14 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t15 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t16 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t17 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t18 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t19 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t20 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t21 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t22 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t23 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t24 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t25 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t26 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t27 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t28 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t29 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t30 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t31 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t32 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t33 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t34 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t35 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t36 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t37 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t38 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t39 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t40 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t41 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t42 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t43 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t44 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t45 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t46 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t47 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t48 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t49 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t50 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t51 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t52 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t53 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t54 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t55 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t56 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t57 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t58 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t59 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t60 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t61 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t62 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t63 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t64 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t65 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t66 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t67 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t68 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t69 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t70 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t71 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t72 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t73 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t74 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t75 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t76 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t77 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t78 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t79 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t80 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t81 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t82 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t83 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t84 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t85 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t86 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t87 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t88 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t89 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t90 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t91 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t92 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t93 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t94 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t95 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t96 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t97 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t98 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t99 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t100 nft-contract ft-contract))
    (print { event: "batch-premint", buyer: tx-sender, count: u100 })
    (ok u100)))

(define-public (premint-150
  (t1 uint) (t2 uint) (t3 uint) (t4 uint) (t5 uint)
  (t6 uint) (t7 uint) (t8 uint) (t9 uint) (t10 uint)
  (t11 uint) (t12 uint) (t13 uint) (t14 uint) (t15 uint)
  (t16 uint) (t17 uint) (t18 uint) (t19 uint) (t20 uint)
  (t21 uint) (t22 uint) (t23 uint) (t24 uint) (t25 uint)
  (t26 uint) (t27 uint) (t28 uint) (t29 uint) (t30 uint)
  (t31 uint) (t32 uint) (t33 uint) (t34 uint) (t35 uint)
  (t36 uint) (t37 uint) (t38 uint) (t39 uint) (t40 uint)
  (t41 uint) (t42 uint) (t43 uint) (t44 uint) (t45 uint)
  (t46 uint) (t47 uint) (t48 uint) (t49 uint) (t50 uint)
  (t51 uint) (t52 uint) (t53 uint) (t54 uint) (t55 uint)
  (t56 uint) (t57 uint) (t58 uint) (t59 uint) (t60 uint)
  (t61 uint) (t62 uint) (t63 uint) (t64 uint) (t65 uint)
  (t66 uint) (t67 uint) (t68 uint) (t69 uint) (t70 uint)
  (t71 uint) (t72 uint) (t73 uint) (t74 uint) (t75 uint)
  (t76 uint) (t77 uint) (t78 uint) (t79 uint) (t80 uint)
  (t81 uint) (t82 uint) (t83 uint) (t84 uint) (t85 uint)
  (t86 uint) (t87 uint) (t88 uint) (t89 uint) (t90 uint)
  (t91 uint) (t92 uint) (t93 uint) (t94 uint) (t95 uint)
  (t96 uint) (t97 uint) (t98 uint) (t99 uint) (t100 uint)
  (t101 uint) (t102 uint) (t103 uint) (t104 uint) (t105 uint)
  (t106 uint) (t107 uint) (t108 uint) (t109 uint) (t110 uint)
  (t111 uint) (t112 uint) (t113 uint) (t114 uint) (t115 uint)
  (t116 uint) (t117 uint) (t118 uint) (t119 uint) (t120 uint)
  (t121 uint) (t122 uint) (t123 uint) (t124 uint) (t125 uint)
  (t126 uint) (t127 uint) (t128 uint) (t129 uint) (t130 uint)
  (t131 uint) (t132 uint) (t133 uint) (t134 uint) (t135 uint)
  (t136 uint) (t137 uint) (t138 uint) (t139 uint) (t140 uint)
  (t141 uint) (t142 uint) (t143 uint) (t144 uint) (t145 uint)
  (t146 uint) (t147 uint) (t148 uint) (t149 uint) (t150 uint)
  (nft-contract <nft-trait>) (ft-contract <ft-trait>))
  (begin
    (asserts! (not (var-get contract-paused)) ERR-PAUSED)
    (try! (contract-call? MARKETPLACE premint t1 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t2 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t3 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t4 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t5 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t6 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t7 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t8 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t9 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t10 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t11 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t12 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t13 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t14 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t15 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t16 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t17 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t18 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t19 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t20 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t21 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t22 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t23 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t24 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t25 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t26 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t27 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t28 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t29 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t30 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t31 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t32 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t33 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t34 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t35 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t36 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t37 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t38 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t39 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t40 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t41 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t42 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t43 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t44 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t45 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t46 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t47 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t48 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t49 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t50 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t51 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t52 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t53 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t54 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t55 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t56 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t57 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t58 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t59 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t60 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t61 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t62 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t63 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t64 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t65 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t66 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t67 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t68 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t69 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t70 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t71 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t72 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t73 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t74 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t75 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t76 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t77 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t78 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t79 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t80 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t81 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t82 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t83 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t84 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t85 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t86 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t87 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t88 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t89 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t90 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t91 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t92 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t93 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t94 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t95 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t96 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t97 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t98 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t99 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t100 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t101 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t102 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t103 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t104 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t105 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t106 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t107 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t108 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t109 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t110 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t111 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t112 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t113 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t114 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t115 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t116 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t117 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t118 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t119 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t120 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t121 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t122 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t123 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t124 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t125 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t126 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t127 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t128 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t129 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t130 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t131 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t132 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t133 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t134 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t135 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t136 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t137 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t138 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t139 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t140 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t141 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t142 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t143 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t144 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t145 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t146 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t147 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t148 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t149 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t150 nft-contract ft-contract))
    (print { event: "batch-premint", buyer: tx-sender, count: u150 })
    (ok u150)))

(define-public (premint-200
  (t1 uint) (t2 uint) (t3 uint) (t4 uint) (t5 uint)
  (t6 uint) (t7 uint) (t8 uint) (t9 uint) (t10 uint)
  (t11 uint) (t12 uint) (t13 uint) (t14 uint) (t15 uint)
  (t16 uint) (t17 uint) (t18 uint) (t19 uint) (t20 uint)
  (t21 uint) (t22 uint) (t23 uint) (t24 uint) (t25 uint)
  (t26 uint) (t27 uint) (t28 uint) (t29 uint) (t30 uint)
  (t31 uint) (t32 uint) (t33 uint) (t34 uint) (t35 uint)
  (t36 uint) (t37 uint) (t38 uint) (t39 uint) (t40 uint)
  (t41 uint) (t42 uint) (t43 uint) (t44 uint) (t45 uint)
  (t46 uint) (t47 uint) (t48 uint) (t49 uint) (t50 uint)
  (t51 uint) (t52 uint) (t53 uint) (t54 uint) (t55 uint)
  (t56 uint) (t57 uint) (t58 uint) (t59 uint) (t60 uint)
  (t61 uint) (t62 uint) (t63 uint) (t64 uint) (t65 uint)
  (t66 uint) (t67 uint) (t68 uint) (t69 uint) (t70 uint)
  (t71 uint) (t72 uint) (t73 uint) (t74 uint) (t75 uint)
  (t76 uint) (t77 uint) (t78 uint) (t79 uint) (t80 uint)
  (t81 uint) (t82 uint) (t83 uint) (t84 uint) (t85 uint)
  (t86 uint) (t87 uint) (t88 uint) (t89 uint) (t90 uint)
  (t91 uint) (t92 uint) (t93 uint) (t94 uint) (t95 uint)
  (t96 uint) (t97 uint) (t98 uint) (t99 uint) (t100 uint)
  (t101 uint) (t102 uint) (t103 uint) (t104 uint) (t105 uint)
  (t106 uint) (t107 uint) (t108 uint) (t109 uint) (t110 uint)
  (t111 uint) (t112 uint) (t113 uint) (t114 uint) (t115 uint)
  (t116 uint) (t117 uint) (t118 uint) (t119 uint) (t120 uint)
  (t121 uint) (t122 uint) (t123 uint) (t124 uint) (t125 uint)
  (t126 uint) (t127 uint) (t128 uint) (t129 uint) (t130 uint)
  (t131 uint) (t132 uint) (t133 uint) (t134 uint) (t135 uint)
  (t136 uint) (t137 uint) (t138 uint) (t139 uint) (t140 uint)
  (t141 uint) (t142 uint) (t143 uint) (t144 uint) (t145 uint)
  (t146 uint) (t147 uint) (t148 uint) (t149 uint) (t150 uint)
  (t151 uint) (t152 uint) (t153 uint) (t154 uint) (t155 uint)
  (t156 uint) (t157 uint) (t158 uint) (t159 uint) (t160 uint)
  (t161 uint) (t162 uint) (t163 uint) (t164 uint) (t165 uint)
  (t166 uint) (t167 uint) (t168 uint) (t169 uint) (t170 uint)
  (t171 uint) (t172 uint) (t173 uint) (t174 uint) (t175 uint)
  (t176 uint) (t177 uint) (t178 uint) (t179 uint) (t180 uint)
  (t181 uint) (t182 uint) (t183 uint) (t184 uint) (t185 uint)
  (t186 uint) (t187 uint) (t188 uint) (t189 uint) (t190 uint)
  (t191 uint) (t192 uint) (t193 uint) (t194 uint) (t195 uint)
  (t196 uint) (t197 uint) (t198 uint) (t199 uint) (t200 uint)
  (nft-contract <nft-trait>) (ft-contract <ft-trait>))
  (begin
    (asserts! (not (var-get contract-paused)) ERR-PAUSED)
    (try! (contract-call? MARKETPLACE premint t1 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t2 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t3 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t4 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t5 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t6 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t7 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t8 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t9 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t10 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t11 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t12 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t13 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t14 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t15 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t16 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t17 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t18 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t19 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t20 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t21 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t22 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t23 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t24 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t25 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t26 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t27 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t28 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t29 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t30 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t31 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t32 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t33 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t34 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t35 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t36 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t37 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t38 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t39 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t40 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t41 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t42 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t43 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t44 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t45 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t46 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t47 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t48 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t49 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t50 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t51 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t52 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t53 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t54 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t55 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t56 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t57 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t58 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t59 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t60 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t61 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t62 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t63 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t64 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t65 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t66 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t67 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t68 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t69 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t70 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t71 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t72 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t73 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t74 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t75 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t76 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t77 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t78 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t79 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t80 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t81 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t82 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t83 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t84 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t85 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t86 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t87 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t88 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t89 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t90 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t91 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t92 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t93 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t94 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t95 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t96 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t97 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t98 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t99 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t100 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t101 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t102 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t103 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t104 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t105 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t106 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t107 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t108 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t109 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t110 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t111 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t112 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t113 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t114 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t115 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t116 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t117 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t118 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t119 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t120 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t121 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t122 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t123 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t124 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t125 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t126 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t127 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t128 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t129 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t130 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t131 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t132 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t133 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t134 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t135 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t136 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t137 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t138 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t139 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t140 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t141 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t142 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t143 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t144 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t145 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t146 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t147 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t148 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t149 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t150 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t151 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t152 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t153 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t154 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t155 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t156 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t157 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t158 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t159 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t160 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t161 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t162 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t163 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t164 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t165 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t166 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t167 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t168 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t169 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t170 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t171 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t172 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t173 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t174 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t175 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t176 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t177 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t178 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t179 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t180 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t181 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t182 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t183 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t184 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t185 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t186 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t187 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t188 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t189 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t190 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t191 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t192 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t193 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t194 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t195 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t196 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t197 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t198 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t199 nft-contract ft-contract))
    (try! (contract-call? MARKETPLACE premint t200 nft-contract ft-contract))
    (print { event: "batch-premint", buyer: tx-sender, count: u200 })
    (ok u200)))

;; Read-only functions
(define-read-only (is-paused)
  (var-get contract-paused))

(define-read-only (get-max-batch-size)
  u200)

(define-read-only (get-contracts)
  {
    marketplace: MARKETPLACE,
    nft: NFT-CONTRACT,
    ft: FT-CONTRACT
  })
